### ISSUE TITLE
Raspbian OS installation issue: python-smbus is not available

### ISSUE THREAD

**Issue by TeslaH2O** [Darmur/bassowl-hat#3]
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

uname -a
Linux moode 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

When running

 wget https://raw.githubusercontent.com/Darmur/bassowl-hat/master/scripts/install_tas5825m_12V_raspios.sh
 chmod a+x install_tas5825m_12V_raspios.sh
 sudo ./install_tas5825m_12V_raspios.sh

I get thsi error:

E: Package 'python-smbus' has no installation candidate

Solution install python3-smbus instead

**Comment by Darmur** [comment]
the scripts were made for an old version of RaspiOS (Buster), they must be updated for working with the latest ones... I will try to have a look.

**Comment by TeslaH2O** [comment]
I fixed by changing line 32 from
`apt -y install python-smbus`
to
`apt -y install python-smbus || apt -y install python3-smbus`

**Comment by Darmur** [comment]
fixed with commit 46cf326ca5bfef0ad7f830298e183c60f17d14dd
